Adds Lighthouse Server Docker Image creation and pushing to Artifactory
Telefonica/qacdco-performance pull request #17
Opened 2023-04-20 13:59 UTC by JavierUhagon

This PR creates a Dockerfile for lhci-server service creation and a Jenkinsfile that will build and push the Docker Image to Artifactory.

2023-04-20 21:41 UTC, rmatei9 requested changes

2023-04-20 21:41 UTC, rmatei9 commented on lighthouse/lhci-server/docker/Dockerfile
> +FROM node:16-bullseye-slim
Hay que modificar el from para que pase por el proxy de artifactory. Si no s hace Lis y se llega al limite de petición diarias dejaría de funcionar las descargas desde dentro de la VPN.

FROM dockerhub.hi.inet/node:16-bullseye-slim

2023-04-20 21:41 UTC, rmatei9 commented on lighthouse/lhci-server/Jenkinsfile
> +            }
No hace falta si no tenéis el repositorio encriptado

2023-04-20 21:41 UTC, rmatei9 commented on lighthouse/lhci-server/Jenkinsfile
> +            }
Si no queries generar release en GitHub hay que borrar esto

2023-04-21 06:51 UTC, JavierUhagon commented on lighthouse/lhci-server/Jenkinsfile
> +            }
He quitado también entonces la parte que checkea la release dentro del repo.

2023-04-24 05:54 UTC, rmatei9 approved these changes
LGTM

2023-04-24 09:22 UTC, merged