Prometheus exporter reporter implementation
Telefonica/qacdco-performance pull request #19
Opened 2023-05-12 12:49 UTC by JoseAlvaradoCevallos

This PR modifies the prometheus exporter to adapt it to the new features added to the performance reporter. It removes the code in charge of creating the graph and keeps the json generator, adding a new parameter in which the title and units of each query are passed.

2023-05-18 08:13 UTC, davidgca commented on prometheus-exporter/README.md
> +    -i: the title of these metrics and their units, separated by commas.
I suggest adding "and their units in the Y axis(X-axis should be always timestamp)"

2023-05-19 10:54 UTC, JoseAlvaradoCevallos commented on prometheus-exporter/README.md
> +    -i: the title of these metrics and their units, separated by commas.
I like this suggestion. Added!

2023-05-19 12:04 UTC, davidgca approved these changes
LGTM

2023-05-22 07:33 UTC, JavierUhagon requested changes
Buen cambio y el código parece que está bastante bien, lo único lo que te he comentado del "estilo" del fichero, el código perfecto.

2023-05-22 12:25 UTC, JoseAlvaradoCevallos commented on prometheus-exporter/script/prometheus_chart_exporter.py
> +
Okey, por ahora lo estandarizamos en 2 saltos lineas. Cambios realizados

2023-05-22 12:29 UTC, merged