Yaml implementation for prometheus exporter
Telefonica/qacdco-performance pull request #20
Opened 2023-10-27 11:17 UTC by JoseAlvaradoCevallos

New implementation of Prometheus Exporter, where a yaml is used to pass a configuration file with all the necessary data, which allows a clearer way to read and correct parameters that we want to pass to this tool.

2023-11-08 12:23 UTC, JavierUhagon requested changes

2023-11-08 12:23 UTC, JavierUhagon commented on prometheus-exporter/script/prometheus_chart_exporter.py
> +        print("generate_graphs=", args.generate_graphs, file=sys.stderr)
Imagino que este Print te lo has dejado, yo creo que estaría bien quitarlo, si vemos importante verbalizar que se están generando las gráficas cambiaria el print para que quede bonito.

```suggestion
```

2023-11-08 12:23 UTC, JavierUhagon commented on prometheus-exporter/script/prometheus_chart_exporter.py
>  import plotly.express as px
Ya no es necesario importar Shlex, ya que has quitado la única vez que se utilizaba (para hacer un split)

```suggestion
import requests
import sys
import shutil
import plotly.express as px
```

2023-11-08 13:40 UTC, JavierUhagon commented on prometheus-exporter/script/ConfigArgs.py
> +            raise yaml.YAMLError(f"authentication: user_password must be in the format 'user:password'")
Si es un string sin variables interpoladas no hace falta que sea un f-string, por temas de estilo y constancia convertiría los f-strings que no necesitan serlo a strings normales
```suggestion
            raise yaml.YAMLError("authentication: user_password must be in the format 'user:password'")
```

2023-11-08 14:50 UTC, JavierUhagon commented on prometheus-exporter/script/ConfigArgs.py
> +            raise yaml.YAMLError(f"metrics: Missing required keys {', '.join(missing_keys)} in a metric.")
La variable missing_keys utiliza la variable metric (una variable sacada de un bucle) estando ya fuera del bucle donde se rellena esa variable, por esto, el valor de missing_keys siempre tendrá solo valores de la última métrica

Es decir, si cualquier métrica (salvo la última) tiene un error en las métricas no se va a levantar la excepción, sino que saldrá un error de este estilo: 
![image](https://github.com/Telefonica/qacdco-performance/assets/107027346/756c114c-8a4a-4430-ae64-e535b8c71668)

2024-01-04 12:16 UTC, JoseAlvaradoCevallos commented on prometheus-exporter/script/ConfigArgs.py
> +            raise yaml.YAMLError(f"authentication: user_password must be in the format 'user:password'")
corregido

2024-01-08 10:37 UTC, JoseAlvaradoCevallos commented on prometheus-exporter/script/ConfigArgs.py
> +            raise yaml.YAMLError(f"metrics: Missing required keys {', '.join(missing_keys)} in a metric.")
corregido

2024-01-15 09:24 UTC, JavierUhagon requested changes

2024-01-15 09:24 UTC, JavierUhagon commented on prometheus-exporter/script/ConfigArgs.py
> +                raise yaml.YAMLError(f"metrics: For key '{key}', expected a string, but got {type(value).__name__} instead.")
Revisando el script para recolectar los parámetros y pasarlos al script principal veo que aquí haces refererencia en la linea 67 a una variable que defines en el loop de la 59, y afaik estaría fuera del scope en el momento que intentas recorrer los items.

No estoy 100% seguro, pero no me encaja del todo esta parte.

2024-01-15 10:07 UTC, JavierUhagon approved these changes
Ahí estaría perfecto. LGTM!

2024-01-15 10:54 UTC, davidgca approved these changes

2024-02-23 08:27 UTC, merged