Resolve locust example conflicts
Telefonica/qacdco-performance pull request #22
Opened 2024-03-04 12:36 UTC by JoseAlvaradoCevallos

# Adding locust framework example to master branch
The ./performance folder of the locust framework example (perf/example branch) is moved to become part of the master structure in the ./locust/locust_example directory.the ./performance folder of the locust framework example (perf/example branch) is moved to become part of the master structure in the ./locust/locust_example directory.

2024-03-04 13:46 UTC, JavierUhagon requested changes

2024-03-04 13:46 UTC, JavierUhagon commented on locust/README.md
> +If you are interested on trying the the Locust framework before you start implementing it in your project we have a simple example of locust framework on directory ```./locust_example```
```suggestion
If you are interested on trying the the Locust framework before you start implementing it in your project we have a simple example of locust framework on directory [./locust_example](./locust_example)
```

Si quieres podríamos poner este fichero así para que se pueda hacer click directamente en el mismo Readme, no lo veo 100% necesario pero no estaría mal

2024-03-04 13:46 UTC, JavierUhagon commented on locust/README.md
> +First you need to go to the example_locust directory:
```suggestion
First you need to go to the locust_example directory:
```

2024-03-04 13:46 UTC, JavierUhagon commented on locust/README.md
> +First you need to create a .env file with the following variables:
```suggestion
Then you need to create a .env file with the following variables:
```

2024-03-04 13:46 UTC, JavierUhagon commented on locust/locust_example/ci/Jenkinsfile
> +            }
El environment del jenkinsfile no tiene los cambios que se le ha hecho al docker-compose ni al commands.txt, no se si el resto del jenkinsfile ha sido modificado, pero habría que mirarlo...

2024-03-04 13:57 UTC, JoseAlvaradoCevallos commented on locust/locust_example/ci/Jenkinsfile
> +            }
corregido, bien visto, gracias!!!

2024-03-04 13:59 UTC, davidgca submitted a review, later dismissed

2024-03-04 14:03 UTC, JavierUhagon requested changes
Okay, he revisado también el jenkinsfile y esto es lo que he visto!

2024-03-04 14:03 UTC, JavierUhagon commented on locust/locust_example/ci/Jenkinsfile
> +            }
Sigue sin estar definida la variable HOME_PATH

Si te fijas en el histórico de la rama perf/example puedes ver lo que estaba puesto sin parametrizar, ese era el valor para el ejemplo usando la máquina que se menciona, si se quiere ejecutar desde el jenkins y no en el local se debería añadir esa variable igual con el valor por defecto o parametrizada...

https://github.com/Telefonica/qacdco-performance/blob/9186858455fb4c60bb7f6fc5246df2b453cff82b/performance/docker-compose.yaml#L9

2024-03-04 14:03 UTC, JavierUhagon commented on locust/locust_example/ci/Jenkinsfile
> +            string(defaultValue: "perf/example", description: 'Performance Project branch', name: 'GIT_BRANCH'),
```suggestion
            string(defaultValue: "master", description: 'Performance Project branch', name: 'GIT_BRANCH'),
```

2024-03-04 14:11 UTC, JavierUhagon approved these changes
Habría que mergear https://github.com/Telefonica/qacdco-performance/tree/perf/example_actions a Master también. Out of scope para esta PR.

LGTM

2024-03-04 14:20 UTC, pablodiazc approved these changes
LGTM

2024-03-04 14:27 UTC, JavierUhagon commented
@pablodiazc 
Antes de mergear en esta rama habría que modificar el post de confluence sobre la metodología de performance 
https://confluence.tid.es/pages/viewpage.action?pageId=73025608#:~:text=Por%20%C3%BAltimo%2C%20se%20ha%20creado%20una%20rama%20en%20el%20repositorio%20del%20framework%20(perf/example)%20que%20contiene%20un%20ejemplo%20funcionando%20de%20un%20escenario%20de%20Locust%20Locust%2Dexample.%20En%20el%20readme%20de%20esta%20rama%2C%20encontrar%C3%A1%20las%20indicaciones%20para%20ejecutar%20el%20escenario%20de%20ejemplo.

¿Se puede ocupar Jose/yo o prefieres modificarlo tú?

2024-03-04 14:59 UTC, merged

2024-03-05 09:19 UTC, davidgca reviewed
LGTM