POC create Azure openAi Assistance
Telefonica/qacdco-performance pull request #24
Opened 2024-03-18 12:41 UTC by davidgca

The aim of this PR is a POC python script that use a openai assistant with this prompt in Spanish :
`Analiza todo el fichero csv y saca una lista seleccionable por el usuario con todos los eventos unicos de la columna label. Despues pediras al usuario que seleccione los eventos que desea y a continuacion sacarás una grafica donde el eje X es la columna timestamp en formato epoch en milisegundos, y el eje y es columna elapsed en milisegundos, de todos los eventos previamente seleccionados, una linea por cada uno de ellos. Pon un leyenda en la grafica con cada nombre` with a csv performance tests example 
the output should be something similar to this:
![load_test_account](https://github.com/Telefonica/qacdco-performance/assets/26218314/e326d762-ca22-4af8-a569-dda5c9ce14fb)

2024-03-18 15:16 UTC, JavierUhagon commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    content="Ejecuta"
¿Qué es exactamente lo de ejecuta?
Lo he visto en un par de lineas más y me surge la duda

2024-03-18 15:26 UTC, JavierUhagon requested changes

2024-03-18 15:26 UTC, JavierUhagon commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +)'''
Esto está completamente comentado, imagino por las pruebas que has hecho, si queremos meterlo en master aunque sea una poc vería bien dejarlo sin comentar!

2024-03-18 15:28 UTC, davidgca commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    content="Ejecuta"
Normal, es poco descripctivo a proposito. El asistente ya tiene su contexto y luego al invocarlo puedes modificar lo mismo, Creo que obliga a poner algo y como cada token cuenta he puesto la uninidad minima que ejecuta el mensaje, hay que darle alguna vuelta a esto y quizas algun punto se pueda optimizar

2024-03-19 10:25 UTC, davidgca commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +)'''
Si lo quiero dejar asi, para que tengamos ya un ejemplo en el codigo funcional . Creo que ya que es una POC podemos dejarlo

2024-03-20 08:33 UTC, JavierUhagon approved these changes

2024-03-20 08:33 UTC, JavierUhagon commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +)'''
Perfecto, pues no veo ningún otro problema!

2024-03-20 09:58 UTC, merged