Qawtp 107 azure chatgpt
Telefonica/qacdco-performance pull request #29
Opened 2024-11-20 12:37 UTC by davidgca

This PR introduces the initial Azure performance analysis with the following steps.
The Python script manages the input and output of the Azure Assistant:
![image](https://github.com/user-attachments/assets/058a626e-858d-4e7c-898f-f87bf955f5c3)

### Features:
1. File Management:
    - Lists and deletes files associated with the assistant.
    - Uploads locust.csv file to the assistant.

2. Assistant Execution:
    - Creates threads and sends user instructions to the assistant.
    - Monitors the status of assistant runs, ensuring execution is tracked until completion.

3. Result Retrieval:
   - Downloads generated images and documents into organized directories (img and docs).

4. Organized Directory Creation:
   - Automatically creates output directories if they do not exist.

This script is designed for easy management of Azure OpenAI Assistant operations and provides a structured workflow for file management, assistant execution, and result retrieval.

Execution evidence can be found in this [ jenkins job execution](https://jenkins.tuenti.io/view/Performance%20testing/job/performance_IA_analizer/33/console),
The resulting image output was: 
![image](https://github.com/user-attachments/assets/9a376662-dc96-4333-95f4-119019f2e661)

2024-11-21 12:12 UTC, JoseAlvaradoCevallos reviewed
La lista de labels a filtrar y representar debería ser dinámica también verdad?
En este caso, si le paso un csv que no contenga esas labels este asistente no hará nada

2024-11-21 12:53 UTC, JoseAlvaradoCevallos commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    manager.list_and_delete_files()
creo el llamado a este método tiene más sentido al final de la ejecución, salvo que necesitemos la última ejecución en casos de error.

2024-11-21 14:02 UTC, davidgca commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    manager.list_and_delete_files()
No, es cuando queremos subir el nuevo CSV cuasndo queremos borrar el antiguo. Ademas pro temas de troublshouting veo util dejar los ficheros tras la ejecucion y solo cuando se lance de nuevo cuando ya se sepa que lo antiguos son obsoletos.

2024-11-21 14:18 UTC, JoseAlvaradoCevallos submitted a review, later dismissed
LGTM!

2024-11-21 15:47 UTC, JavierUhagon commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    manager.download_results(thread_id=thread_id)
Una tontería pero no hay una nueva linea al final del archivo

2024-11-21 15:48 UTC, JavierUhagon requested changes

2024-11-21 15:48 UTC, JavierUhagon commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    API_KEY = "cf56ce6ffb6d418f9c56793b9e7830ed"
¿Es esta API_KEY la de verdad?
Si lo es, toca revocarla, este repo es público y ya se ha filtado...

2024-11-21 17:00 UTC, davidgca commented on ia/AzureOpenAI/Assistants/PerformanceAnalizer.py
> +    API_KEY = "cf56ce6ffb6d418f9c56793b9e7830ed"
ya esta revocada. En jenkins vamos a hacerlo con un vault que ya he pedido

2024-11-22 07:02 UTC, JavierUhagon submitted a review, later dismissed

2024-11-22 10:44 UTC, JoseAlvaradoCevallos approved these changes

2024-11-22 10:53 UTC, pablodiazc approved these changes
LGTM

2024-11-22 11:06 UTC, merged